name: Manga Scraper

on:
  schedule:
    - cron: '*/5 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository content to GitHub runner

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Install the Python version needed

      - name: Install Python packages
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Execute scripts
        run: |
          python manganelo_scraper.py
          python postprocessing.py
          python final_post.py
          python telegram_bot.py
        env:
          FINAL_INFO_FILE: ${{ secrets.FINAL_INFO_FILE }}
          CSV_DIR: ${{ secrets.CSV_DIR }}
          SAMPLES_DIR: ${{ secrets.SAMPLES_DIR }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
